Return ZLP on empty requests of descriptors
greatscottgadgets/luna pull request #140
Opened 2021-10-08 17:18 UTC by twam

2021-11-12 18:28 UTC, straithe commented
Thank you for your Pull Request! I have assigned a reviewer to this issue and it may take them some time to get to reviewing this. In the meantime, would you be willing to work on addressing the conflicts with this PR?

2021-11-13 10:33 UTC, twam commented
@straithe sure: Rebased on lastest main.

2021-11-13 16:47 UTC, straithe commented
Thank you very much! I do have a reviewer assigned to this PR. It might take them a bit of time to get to this, but please know that we have seen this PR and appreciate your work.

2021-11-15 17:04 UTC, miek requested changes
Thanks for the PR!

I've added a couple of comments inline & made the proposed changes here: https://github.com/miek/luna/commit/822423d26e34b1e4c27ac73374a90b8e57eddf65. Let me know what you think.

2021-11-15 17:33 UTC, twam commented
Checked your suggestion solution and really like it! Suggest to merge that instead.

2021-11-15 17:33 UTC, twam commented on luna/gateware/usb/usb2/descriptor.py
> +                is_valid_send = (length > 0) | (self.start_position > 0)
Good point. Haven't checked that, just extended. :)

2021-11-15 17:44 UTC, miek commented
Merged manually with those changes, thanks again!

2021-11-15 17:44 UTC, closed without merging