applets: add a bi-directional bulk_speed_test applet
greatscottgadgets/luna pull request #205
Opened 2023-05-23 09:39 UTC by antoinevg

This PR adds a new applet that is able to form a bi-directional bulk speed test.

I don't have access to SuperSpeed hardware so I thought it best to implement this separately to the `bulk_in_speed_test.py` applet for now.

New features added:

* Addition of a new OUT endpoint. (Added bonus: the speed test device will no enumerate under macOS)
* Vendor request handler to manage the switch between IN/OUT test.
* Data sent by the IN test is now an 8-bit counter rather than zeros.
* OUT test mirrors received data on device LED's and PMOD A.

There is one area where I am not 100% sure I'm doing the right thing in the gateware implementation and that is the logic for when a given IN or OUT test is inactive:

**IN test:**

https://github.com/antoinevg/luna/blob/791498f1eabb3632453770a5a3c5f7d3876e3c2a/applets/bulk_speed_test.py#L229-L236

**OUT test:**

https://github.com/antoinevg/luna/blob/791498f1eabb3632453770a5a3c5f7d3876e3c2a/applets/bulk_speed_test.py#L250-L264

2023-06-06 07:07 UTC, antoinevg commented
I've removed the vendor request handler without any ill-effects, tx!

Let's wait for https://github.com/greatscottgadgets/luna/pull/207 to get merged into main and then I'll update the PR to match the new code layout.

2023-06-09 13:12 UTC, antoinevg commented
I've rebased the PR to take #207 into account.

Also:

* Renamed `applets/bulk_in_speed_test.py` to `applets/bulk_speed_test.py`
* Added an exclusion for SuperSpeed devices so that only the IN test gets performed for them.
* Reworked the logic for `bulk_speed_test.__main__` to make it a little less verbose.

2023-10-03 16:01 UTC, miek requested changes
This looks good to me! There's just a minor fix needed that I've added inline.

2023-10-04 06:40 UTC, antoinevg commented on luna/gateware/applets/speed_test.py
> +        leds   = Cat(platform.request_optional("led", i, default=NullPin()) for i in range(6))
Tx @miek, I've made the update and rebased against main!

2023-10-10 15:37 UTC, merged